#!/bin/sh

groupId="org.janelia.saalfeldlab"
artifactId="paintera-conversion-helper"
version="${VERSION:-0.0.1-SNAPSHOT}"
mainClass="org.janelia.saalfeldlab.conversion.CommandLineConverter"

jrun \
    ${JAVA_OPTS} \
    "${groupId}:${artifactId}:${version}:${mainClass}" \
    $@
