#!/usr/bin/env sh

chown root:wheel "INSTALL_LOCATION"
chmod a+rX "INSTALL_LOCATION"
chmod +r "APP_LOCATION/"*.jar

ln -s "$(realpath 'APP_LOCATION/../MacOS/paintera-convert')" /usr/local/bin/paintera-convert

exit 0