#!/usr/bin/env sh

chown root:wheel "INSTALL_LOCATION"
chmod a+rX "INSTALL_LOCATION"
chmod +r "APP_LOCATION/"*.jar

cat > /usr/local/bin/paintera-convert <<EOF
 #!/usr/bin/env sh
 "$(realpath 'APP_LOCATION/../MacOS/paintera-convert')"
EOF
chmod +x /usr/local/bin/paintera-convert


exit 0