# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Installers

on:
  push:
    tags:
     - "paintera-conversion-helper-*.*.*"
     - "prerelease-*"
  workflow_dispatch:



env:
  DEV_IDENTITY: BXPZTQZ35S # Your Apple Dev identity, something like BXPZTQZ35S
  PRIMARY_BUNDLE_ID: org.janelia.saalfeldlab.PainteraConvert # Unique to your app, often the launcher class

jobs:
  build_installers:
    name: Build Installers
    uses: ./.github/workflows/build-installers.yml

  create_release:
    needs: build_installers
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Set Version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Rename Artifacts
        run: |
          mv Paintera-windows-latest-*/*.msi Paintera-${{ env.VERSION }}-Windows.msi
          mv PainteraConvert-ubuntu-latest-*/*.deb PainteraConvert-${{ env.VERSION }}_x86_64.deb
          mv PainteraConvert-macos-latest-*/*.pkg PainteraConvert-${{ env.VERSION }}-MacOS.pkg
          mv PainteraConvert-macos-14-*/*.pkg PainteraConvert-${{ env.VERSION }}-MacOS-AppleSilicon.pkg
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Paintera Convert ${{ env.VERSION }}
          tag_name: ${{ github.ref }}
          prerelease: false
          files: |
            PainteraConvert-${{ env.VERSION }}-Windows.msi
            PainteraConvert-${{ env.VERSION }}_x86_64.deb
            PainteraConvert-${{ env.VERSION }}-MacOS.pkg
            PainteraConvert-${{ env.VERSION }}-MacOS-AppleSilicon.pkg